%% ANALYZE BUILD DIFFERENCES
% 分析対象：PCごとにビルドされたバイナリの差異原因と Git 戦略を検討

clear; clc;

fprintf('==========================================================================\n');
fprintf('BUILD REPRODUCIBILITY ANALYSIS\n');
fprintf('==========================================================================\n\n');

%% 1. バイナリメタデータ比較
fprintf('【1】MEX バイナリのメタデータ比較\n');
fprintf('--------------------------------------------------------------------------\n');

bin_dir = fullfile(pwd, '..', 'cpp', 'bin');
binary_file = fullfile(bin_dir, 'mex_run_eskf.mexw64');

if exist(binary_file, 'file')
    info = dir(binary_file);
    fprintf('This PC バイナリ:\n');
    fprintf('  ファイル名: %s\n', info.name);
    fprintf('  サイズ: %,d bytes (%.2f KB)\n', info.bytes, info.bytes/1024);
    fprintf('  変更日時: %s\n', datestr(info.datenum));
    
    % MD5 ハッシュ（terminalで確認済み）
    fprintf('  MD5: 15269c6a49f9c945b31c9c824eecd0b2 (当環境)\n');
    fprintf('\nOther PC バイナリ（会話記録から）:\n');
    fprintf('  サイズ: 976,384 bytes (~976 KB)\n');
    fprintf('  MD5: c5298d6b740b9ec900681904c5ce46e4 (初期) or 22fbd8cd850dc0d6f6907636ae628011 (再ビルド)\n');
    fprintf('  サイズ比: 976 KB / 155 KB = 6.3倍 差異\n');
else
    fprintf('バイナリファイルが見つかりません: %s\n', binary_file);
end

fprintf('\n\n【1.1】バイナリサイズ差の可能性のある原因\n');
fprintf('--------------------------------------------------------------------------\n');

causes = {
    '①　デバッグシンボル', ...
    '     - Other PC: デバッグ情報を含む (.pdb, embedded debug symbols)', ...
    '     - This PC: デバッグ情報を剥離済み、または -DNDEBUG でビルド', ...
    '     差異: 400-600 KB は典型的', ...
    '', ...
    '②　ランタイムライブラリのリンク', ...
    '     - Other PC: MSVCR1XX.dll を静的リンク (Runtime Library: /MT)', ...
    '     - This PC: 動的リンク (Runtime Library: /MD)', ...
    '     差異: 100-300 KB', ...
    '', ...
    '③　最適化レベルの差異', ...
    '     - Other PC: -O0（最適化なし）または /Od', ...
    '     - This PC: -O（最適化あり）', ...
    '     差異: 20-50 KB（コード生成サイズ）', ...
    '', ...
    '④　MATLAB MEX コンパイラの差異', ...
    '     - Windows Build版（26100 vs 26200）で MSVC version が異なる可能性', ...
    '     - MinGW vs MSVC のコンパイラ選択', ...
    '', ...
    '⑤　不要なシンボルの含有', ...
    '     - Other PC: export all symbols (-Wl,--export-all-symbols)', ...
    '     - This PC: essential symbols only', ...
    };

for i = 1:length(causes)
    fprintf('%s\n', causes{i});
end

fprintf('\n\n【2】コンパイルフラグの確認（build_mex.m より）\n');
fprintf('--------------------------------------------------------------------------\n');

fprintf('現在のビルド設定:\n');
fprintf('  compile_opts = {"-O", "-DNDEBUG", "-DKALMAN_NO_STANDALONE"}\n');
fprintf('  Windows COMPFLAGS = "/utf-8"\n');
fprintf('  Include paths: Lib/ ディレクトリの複数パス\n');
fprintf('  MEX linking: デフォルト (通常は -lmx -lengine -lmwm_dispatcher)\n\n');

fprintf('⚠️  不足している可能性のある診断情報:\n');
fprintf('  □ Other PC の MSVC version (例: MSVC 2022 vs 2019)\n');
fprintf('  □ Other PC の /MT (静的C Runtime) vs /MD (動的)\n');
fprintf('  □ Other PC の COMPFLAGS 設定 (/O2 vs /Od など)\n');

fprintf('\n\n【3】再現性のためのチェックポイント\n');
fprintf('--------------------------------------------------------------------------\n');

checks = {
    '✓ build_mex.m で両PC同じコード呼び出し → 確認済み', ...
    '✓ Git commit hash 同じ (f3b451b2...) → 確認済み', ...
    '✓ MATLAB version 同じ (R2025b 25.2.0) → 確認済み', ...
    '⚠ Windows Build version 異なる (26200 vs 26100) → 診断必要', ...
    '⚠ C++ Compiler version 不明 → dumpbin で確認可', ...
    '⚠ Runtime Library リンク形式 不明 → PE header で確認可', ...
    '⚠ デバッグシンボル含有有無 不明 → binaries を strings/objdump で検査', ...
    };

for i = 1:length(checks)
    fprintf('%s\n', checks{i});
end

fprintf('\n\n【4】Git 戦略の比較\n');
fprintf('--------------------------------------------------------------------------\n\n');

strategies = {
    'オプション A: .gitignore に .mexw64 を追加（推奨）', ...
    '  - 利点:', ...
    '    □ 各環境で自動的に最適化される', ...
    '    □ バージョン管理を単純化（ソースのみ管理）', ...
    '    □ CI/CD パイプラインに統合可能', ...
    '    □ マージコンフリクトなし', ...
    '  - 欠点:', ...
    '    □ 初回チェックアウト後 build_mex.m 実行が必須', ...
    '    □ ビルド環境がない場合（例：学生PCなど）は不可', ...
    '', ...
    'オプション B: CI/CD でプリコンパイル（推奨度中）', ...
    '  - GitHub Actions / GitLab CI でビルド → Release に .mexw64 を保存', ...
    '  - 利点:', ...
    '    □ 1つの信頼できるビルド環境', ...
    '    □ 複数MATLAB version/OS への対応可', ...
    '  - 欠点:', ...
    '    □ CI/CD設定が必要', ...
    '    □ セットアップ時間が増加', ...
    '', ...
    'オプション C: 環境ごとのバイナリディレクトリ（非推奨）', ...
    '  - bin_R2025b_Win26200/, bin_R2025b_Win26100/ に分離', ...
    '  - 利点: 環境別にバイナリ選択可能', ...
    '  - 欠点: リポジトリが肥大化、管理負荷が大', ...
    '', ...
    'オプション D: Docker コンテナで標準化ビルド', ...
    '  - 全環境で同じ Docker イメージ使用', ...
    '  - 利点: 完全な再現性', ...
    '  - 欠点: Docker 導入が必須', ...
    };

for i = 1:length(strategies)
    fprintf('%s\n', strategies{i});
end

fprintf('\n\n【5】推奨事項（Summary）\n');
fprintf('--------------------------------------------------------------------------\n\n');

fprintf('【即座の対応】\n');
fprintf('1. .gitignore に追加:\n');
fprintf('   kalman/cpp/bin/*.mexw64\n');
fprintf('   kalman/cpp/bin/*.mexa64 (Linux 対応の場合)\n\n');

fprintf('2. README に追記:\n');
fprintf('   「初回セットアップ時に、kalman/cpp/build/ で build_mex() を実行してください」\n\n');

fprintf('3. build_mex.m に verbose mode を追加:\n');
fprintf('   - Compiler type / version の出力\n');
fprintf('   - Runtime Library リンク方式の出力\n');
fprintf('   - ビルド環境情報をログに記録\n\n');

fprintf('【中期目標】\n');
fprintf('1. GitHub Actions で MATLAB ビルドを自動化\n');
fprintf('   - Windows + MATLAB R2025b で標準ビルド\n');
fprintf('   - Release に .mexw64 をアップロード\n\n');

fprintf('2. build_mex_verbose.m を作成:\n');
fprintf('   - dumpbin / strings の自動実行\n');
fprintf('   - バイナリメタデータをレポート出力\n\n');

fprintf('【検証コマンド（Other PC で実行）】\n');
fprintf('1. デバッグシンボル有無確認:\n');
fprintf('   dumpbin /pdata C:\\...\\mex_run_eskf.mexw64 | head -20\n\n');

fprintf('2. 含有シンボル一覧:\n');
fprintf('   strings mex_run_eskf.mexw64 | head -50\n\n');

fprintf('3. PE Header 情報:\n');
fprintf('   dumpbin /headers mex_run_eskf.mexw64 | grep -E "Debug|Runtime"\n\n');

fprintf('\n=== 分析完了 ===\n\n');
